# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ce9ad224851e283bbe4dc1f1b97c5783bc8492ecdde3b4aaea6f7cb19bc76f4e677b55428edfb1432bd85e486f518a92c5b54d970f326135b38559c338a7ab5

test:
  secret_key_base: 7ca1e1518e105ea62cb137cc30c8fe442bb590aa024aa09367e7b4db95deae3410e1edecacb96d7944c1054c4010592f573bdc3f47eaab56d7806ba7a594b7f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
