# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb618b4314366b28081acc15524f7a61ea7129d62588c45a79c54d72a35fd85463600dd7551b281f88b78aab8a12012295c2ff8cdf27672816537df13b76d1fe

test:
  secret_key_base: 61dbc9603150ede470740a27057b06216a82dee7257030c364ea81c228c152030a44d11fb6256c8a37d355c4b1d32b33d34d8928b1448d9487be5e856745cf61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
