# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ffcb2f93501a646711c2da0fcf616b3abf77d11f6ff169f0830abd64aee54a87f3a44689cfd5fb061b8f6e2b0835645c083bbfa64f86d07834f9304ba67a68

test:
  secret_key_base: 75620be5301b88b9efa944e50150e8f3973bfb64c9cfdc74e46b70e7bc6fe4a34609c3e44ecdba8dcaadd15e302c8c91737ee0f5a2daba42bd4567d3f05ed1b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
