# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eccbb5a3a9087833148292d19d99257559d21f56462258db1b4008d9bdc98f2c1cdd02ce3a25898fb4caad82dec76429343fafa033fbdad12a8b39942033b8b3

test:
  secret_key_base: f878797104ce601dc060fd0eaad5dc8f975738a5926bbad3dbbc6bed3c9301b88a39db909ab082c0527b2be1da9f1864f757df3d53950ed7cea2e85ae5b25a45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
