# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42aa795a861483d4495b13d579828f9631695ba9ab2aba52c0d06f4600c6e5fa59b1ed54ac81ac87b6d3dad296d4b1656c14159b84067d4024a8a2e019702c68

test:
  secret_key_base: 9e06d6978d6e32569d4735ee3e8fededfc035972699d9793f552d796f241115c4de07cc7e6cc5f03cdf485074eb9f014b899f4ef27e72580fd33c83dfe7de4b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
