# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bae7cc49ed5d23c5ed62aa3d820fade5469f7c9bb6da77d33c9e2f5060af009bf215760416a25aa23f9c96dd33da0e9fcbf2ec0a60b22a4f79d6f115acc3d53

test:
  secret_key_base: 404d4f259f30e356b0ea499b54eb8ee9d4629f0760a11eed2de467638e43bf53f43b2ac93643006a2b1d22b1199c591991a24bbaafd11ae7d89b2523e97c5b47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
