# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff676935a56f18390a6319e3e0bae43fa1b0db477532b0a5bfaf1f98e251f633828cca37707a3ea94b2a451bfbdfc57bccbf01b55bdaac299257c143ee1df7dc

test:
  secret_key_base: 229ab916e8e2b6dad5de96fc519d74310b295e310a983245381a7c88fe7215acc6cae003fcb5aaa1824a5b9f081569170d5c7097da304f67781a50a189fcf9ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
