# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f53a7f6f448d7a675bba86ca5a3b80183721aff5e56d31be3608831878eb3d99807b0b992044963b5b819807602aba4695b7c4a6876f617faf6cf30a201c92ac

test:
  secret_key_base: 06c1190c90b4914835a5d40c2c20aff798e1c679d28112765b0bd21bafb9f15260928ec5a2c2f3fe409f88daec77d3c790bfd26cd5f856927d96e6126d28c410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
