# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c47755f9d427f77267b0b58a0bb57a3e2b8e14352b5901f5a6a3dcfa765c6d705bd37d29249a82a9985d356bcfac59e4e3bfa19a36b7d138768ce9ad55dfb7

test:
  secret_key_base: 022c6eca25fb613f6ca161131afc777fd261a7305d97fc647af5eca371848fe9dd8b917dc8d2ee539e3259bfa8fde9376551a0e89339efda5b8a783fd763f04f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
