# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b95217aa08620abcdc55062c8d9621cd2261890f286bd98bde8ad323e15ca2b9f5cb0dcffdc7035ed1dfdd85fb3e5839a3a691e64b7519ab05088fc1c806f3d

test:
  secret_key_base: 77c159fa525cb89899e8dc5d8a611e7bb182de260d0c58cceb50bf36ed79154e8a03c4d4d7af34486835c67bd2afc37a53bf968115c383faff5e90d2d0665129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
