# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 658f4c03fba3b8efcff0eaa385cb807af555bb136b314954ec9aae5385f72a1c9c486919954565caf074fd378b6e48ab4047fd9d6b0adba921af14b2d435bade

test:
  secret_key_base: 920592ee5af333af4630daea94eb5bab12cc8399affb85e452e9c86a6e7826a9989da0466044b2af7cdae62917c3b7d7a7263873aad2ea2ee20f6694eca36795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
