# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c48d28dadccd9b2717ebfbd38085ed7ce45871f06f4b3f6dbf587f4ee7cdb723e97f475a924d546af050b54cb90bc655b3bb34db70fd1931b75bdfd4ece59b4

test:
  secret_key_base: d67efad2a84f62f3c07f76b3950d50df33fe28c53ce64708236c53bb71618b3ca43578e771cbc0dd89b25dbd6c500b5d05cb169eefc5429826de734f92f402a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
