# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98dde7dc02ec853c2ee5b24ac80a87fe7a80d40e2335b58b0a897ca204f6d46a051dc057240416dcfb56525ae084ae16bec0d643daeee79850f0eb6594dbfa18

test:
  secret_key_base: 7eb3e61ecd7b9a8f96e8eb0fd0ac3750f4385d75be5f896422b984f7c135c144ea74d0fb9120831eec5c307c129b9cd9fe5afa99f8fa5f1ae0d7554332cf72e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
