# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42c9f7f335318827996d36bfbc5a8dd327583195c2cb81f0a6d8b951583da5831fe0c993a7b0fb23af65329861bccf180de0fe4dbddf39e888ad5d9172b836e4

test:
  secret_key_base: ac58be020f6e4c83dbc7fa542d01b715b7c5865671a7ca3c346b8c7672e67d5073221b29e68744920eeb33c1974c1160d800b133d9283288aaa1e300b5f648ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
