# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492294f04a762e3248a502a4203021c1e05d4d26764de0cb9a819cc95f5466cb1f51929a6f6a603f37406381d7256231b285193da83df6b28036d0ebe4fbbbb3

test:
  secret_key_base: 13c4a279a58bc2cf5524d6a1b6dda9103a1a09ef24d70cbd4b0dff8578d8b9942c2a324d14dc8011836d8ed5724020b261fb7c3d662aba31b812c64467cac5f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
