# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e527c8d451fd4081132820676cb944591adb8feb95dcba13d839b69af6b542254e2e4db07e53bcac0885393efb0ec050c011670f218a0fd2b49b8cd35cbb4594

test:
  secret_key_base: d2626e71c8cd10c03bfc2edf10dd44e94d9aea89cd3c3dbbf79674095dfe6a5ad60ff2623bc992a96bf208f5df4c113b7c4b6591171b442c81e6ba794c045ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
