# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cea2609b5035aa89ae3e4675e61b33022bcd6b8c16f074bbfaed8a8622572598fae044ec620ba111c8f26c4e5e0101444ebaf43325998e03df126f44cb9e449

test:
  secret_key_base: 5ee5931c0d075a6debecc881848cd4f51f13f6eef225f6b3e94bb1e3144786b338f880f8f650f7ec8a91fda02464633d4db803fda4b1292c9f7c418c05fdf6c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
