# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8be85cfba209e0d214708f273fb32b7991ea5567548fc6d2fd762a97655a846c48ee9ea8e5c96bf133d403fc43fb8cd518e59496eb60e6e95d3681f8f4415b1

test:
  secret_key_base: ac2af51ee020445fb6f359006b2b63ede61f6391bcb9ceb24e6b96594201c52507101823d9e70474015acade12c814558ac3f31e2af590422e74f332c2e88487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
