# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ccef3b672dc76648f8ec748d09015071b4d487affc03fad12a31700e5534143d10d993e486c3f4404026ecb141695101dcc0ea9faf60c08db75af2d3473cad

test:
  secret_key_base: 256c03be958fd71783e2f30da442560fb5fb6e3af2e0dad7bfc43db130c4ab7d2dedaa2dcbd9577d4c941d20bd798f2aa42645cfe9d7c91e277e187808147a41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
