# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 302aca7a0babc78ea463fc1f9938fd05e1ea9da70d4d066fb0a2099b5a5fba9382133675472f23bb01ce17766242a176d3d20578f64d10241dbcf9217e65e327

test:
  secret_key_base: c15b37136aa318f84a5bcf6d210221c898b69dcbfbb9610d9888798681768e7004d9f039caa244192d806ca7e8059706146a3c066a7f8ddd4db6bdb2d6704106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
