# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7e3f2f3832c87a0c0d9378f4e5ecd49ed63c0b5b66a829c33d0d70134c925346935fba126b51314941ead572c32075c117bf03cc4530907a1123f6e5a44351b

test:
  secret_key_base: f4268b2e54d94494ff9663a1c684764b4b2709dadcf386541f18df4a70b0d49e9956ed89324b43b8ea018cc8a569e4f1fadf2bfa7162cd3ffc397f48d7ea1c5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
