# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc5e35c0475f9a2b33c1e4dcd388705be7c89be10dcebb39affa21cd20de7beff0ca821b4ffb0dcded98020fd05f745287a105e377aa73c6e98d36ddfc573955

test:
  secret_key_base: d011d9d465593290395beacb106306b63ebe3b6e95fcef008addfcfe604eafefd2e34de4bd335ee2b9adc83079297a4282d66d4201a0a4ae3a465e0ffe116731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
