def get_comment_data
  comment_data =
    {"post_1"=>[{:comment=>"The game's not big enough unless it scares you a little. I think you've let your personal feelings cloud your judgement. Maybe we better talk out here; the observation lounge has turned into a swamp. Captain, why are we out here chasing comets?"}, {:comment=>"Wouldn't that bring about chaos? Wait a minute - you've been declared dead. You can't give orders around here. I recommend you don't fire until you're within 40,000 kilometers. I'm afraid I still don't understand, sir."}, {:comment=>"A surprise party? Mr. Worf, I hate surprise parties. I would *never* do that to you. For an android with no feelings, he sure managed to evoke them in others. Shields up! Rrrrred alert! Now we know what they mean by 'advanced' tactical training."}],

    "post_2"=>[{:comment=>"Wait a minute - you've been declared dead. You can't give orders around here. Yes, absolutely, I do indeed concur, wholeheartedly! I'll alert the crew. We could cause a diplomatic crisis. Take the ship into the Neutral Zone Why don't we just give everybody a promotion and call it a night - 'Commander'?"}, {:comment=>"Now we know what they mean by 'advanced' tactical training. When has justice ever been as simple as a rule book? Commander William Riker of the Starship Enterprise. Computer, lights up! Wait a minute - you've been declared dead. You can't give orders around here."}],

    "post_3"=>[{:comment=>"I'd like to think that I haven't changed those things, sir. The look in your eyes, I recognize it. You used to have it for me. Some days you get the bear, and some days the bear gets you. Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody. You're going to be an interesting companion, Mr. Data. Wouldn't that bring about chaos? The Enterprise computer system is controlled by three primary main processor cores, cross-linked with a redundant melacortz ramistat, fourteen kiloquad interface modules."}]}
  return comment_data
end
