def get_post_data
  post_data = {
    "post_1" => {
              title: "Hello World",
              user: "Lisa B.",
              article: "Flair is what marks the difference between artistry and mere competence. I've had twelve years to think about it. And if I had it to do over again, I would have grabbed the phaser and pointed it at you instead of them. I can't. As much as I care about you, my first duty is to the ship. Now, how the hell do we defeat an enemy that knows us better than we know ourselves? Why don't we just give everybody a promotion and call it a night - 'Commander'? When has justice ever been as simple as a rule book? Captain, why are we out here chasing comets? Damage report! How long can two people talk about nothing? I recommend you don't fire until you're within 40,000 kilometers. Not if I weaken first. What? We're not at all alike! Commander William Riker of the Starship Enterprise. I will obey your orders. I will serve this ship as First Officer. And in an attack against the Enterprise, I will die with this crew. But I will not break my oath of loyalty to Starfleet. Fate protects fools, little children and ships named Enterprise.",
            },
    "post_2" => {
              title: "Another Monday...",
              user: "Lisa B.",
              article: "I suggest you drop it, Mr. Data. Smooth as an android's bottom, eh, Data? Ensign Babyface! Not if I weaken first. Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody. Congratulations - you just destroyed the Enterprise. I recommend you don't fire until you're within 40,000 kilometers. I'd like to think that I haven't changed those things, sir. What's a knock-out like you doing in a computer-generated gin joint like this? You bet I'm agitated! I may be surrounded by insanity, but I am not insane. This is not about revenge. This is about justice. Computer, lights up! Could someone survive inside a transporter buffer for 75 years? I'll be sure to note that in my log. Sorry, Data. Mr. Worf, you sound like a man who's asking his friend if he can start dating his sister. We could cause a diplomatic crisis. Take the ship into the Neutral Zone About four years. I got tired of hearing how young I looked. Shields up! Rrrrred alert! You enjoyed that. The Enterprise computer system is controlled by three primary main processor cores, cross-linked with a redundant melacortz ramistat, fourteen kiloquad interface modules. I've had twelve years to think about it. And if I had it to do over again, I would have grabbed the phaser and pointed it at you instead of them. Is it my imagination, or have tempers become a little frayed on the ship lately? The look in your eyes, I recognize it. You used to have it for me.",
            },
    "post_3" => {
              title: "Tuesday Morning...",
              user:"Lisa B.",
              article: "Your head is not an artifact! About four years. I got tired of hearing how young I looked. When has justice ever been as simple as a rule book? Yes, absolutely, I do indeed concur, wholeheartedly! For an android with no feelings, he sure managed to evoke them in others. Why don't we just give everybody a promotion and call it a night - 'Commander'? Mr. Crusher, ready a collision course with the Borg ship. Could someone survive inside a transporter buffer for 75 years? Some days you get the bear, and some days the bear gets you. Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody. Not if I weaken first. Damage report! Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody. I've had twelve years to think about it. And if I had it to do over again, I would have grabbed the phaser and pointed it at you instead of them. You bet I'm agitated! I may be surrounded by insanity, but I am not insane. This is not about revenge. This is about justice. Travel time to the nearest starbase? Computer, belay that order. Did you come here for something in particular or just general Riker-bashing? That might've been one of the shortest assignments in the history of Starfleet. I think you've let your personal feelings cloud your judgement. I'll be sure to note that in my log. I can't. As much as I care about you, my first duty is to the ship. You're going to be an interesting companion, Mr. Data. Captain, why are we out here chasing comets?",
            }
    }
  return post_data
end
