# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.destroy_all
Comment.destroy_all

Post.create(title: 'The first post', post: 'Per vulputate neque. Tincidunt libero viverra eros vehicula lectus tincidunt amet nulla. Odio fusce pharetra. Hendrerit arcu elit vulputate suspendisse nonummy et tortor donec. Laoreet luctus aliquam cras sem mattis. Orci porttitor elit vestibulum fermentum integer. Molestie dis ac. Lacus ornare ac. Eget leo nec. Dictum ipsum ultricies massa non commodo pellentesque wisi lorem luctus congue ac justo pede congue mattis sociosqu ultricies fermentum nec sed ad vivamus torquent metus parturient lorem dolores ac non. Eget lacus pellentesque. Interdum non non. Sapien netus dignissim. In lacus interdum netus at leo amet tristique lobortis. Eget vivamus pulvinar nibh ac mi. Et at pellentesque. Blandit elit laoreet neque id orci. Adipiscing feugiat habitasse. Leo metus pellentesque. Ante eu tellus ornare nec quisque.', date: '1/1/00')
Post.create(title: 'The second post', post: 'Per vulputate neque. Tincidunt libero viverra eros vehicula lectus tincidunt amet nulla. Odio fusce pharetra. Hendrerit arcu elit vulputate suspendisse nonummy et tortor donec. Laoreet luctus aliquam cras sem mattis. Orci porttitor elit vestibulum fermentum integer. Molestie dis ac. Lacus ornare ac. Eget leo nec. Dictum ipsum ultricies massa non commodo pellentesque wisi lorem luctus congue ac justo pede congue mattis sociosqu ultricies fermentum nec sedad vivamus torquent metus parturient lorem dolores ac non. Eget lacus pellentesque. Interdum non non. Sapien netus dignissim. In lacus interdum netus at leo amet tristique lobortis. Eget vivamus pulvinar nibh ac mi. Et at pellentesque. Blandit elit laoreet neque id orci. Adipiscing feugiat habitasse. Leo metus pellentesque. Ante eu tellus ornare nec quisque.', date: '1/2/00')
Post.create(title: 'The third post', post: 'Per vulputate neque. Tincidunt libero viverra eros vehicula lectus tincidunt amet nulla. Odio fusce pharetra. Hendrerit arcu elit vulputate suspendisse nonummy et tortor donec. Laoreet luctus aliquam cras sem mattis. Orci porttitor elit vestibulum fermentum integer. Molestie dis ac. Lacus ornare ac. Eget leo nec. Dictum ipsum ultricies massa non commodo pellentesque wisi lorem luctus congue ac justo pede congue mattis sociosqu ultricies fermentum nec sedad vivamus torquent metus parturient lorem dolores ac non. Eget lacus pellentesque. Interdum non non. Sapien netus dignissim. In lacus interdum netus at leo amet tristique lobortis. Eget vivamus pulvinar nibh ac mi. Et at pellentesque. Blandit elit laoreet neque id orci. Adipiscing feugiat habitasse. Leo metus pellentesque. Ante eu tellus ornare nec quisque.', date: '1/3/00')
