# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.destroy_all
Comment.destroy_all

Post.create(user: "Wikipedia", title: "Hamburger", photo_url: "http://www.hamburgerhamlet.com/wp-content/uploads/2014/11/the-hamburger-hamlet-sherman-oaks-40.jpg", content: "A hamburger or burger is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread roll or bun. The patty may be pan fried, barbecued, or flame broiled. Hamburgers are often served with cheese, lettuce, tomato, bacon, onion, pickles, or chiles; condiments such as mustard, mayonnaise, ketchup, relish, or \"special sauce\"; and are frequently placed on sesame seed buns. A hamburger topped with a slice of cheese is called cheeseburger.")
Post.create(user: "Wikipedia", title: "Pizza", photo_url: "http://www.athenaspizzaamherst.com/wp-content/uploads/2013/05/front-1-1008x500.jpg", content: "Pizza is a yeasted flatbread popularly topped with tomato sauce and cheese and baked in an oven. It is commonly topped with a selection of meats, vegetables and condiments. The term was first recorded in the 10th century, in a Latin manuscript from Gaeta in Central Italy.The modern pizza was invented in Naples, Italy, and the dish and its variants have since become popular and common in many areas of the world.")
Post.create(user: "Wikipedia", title: "Fried Chicken", photo_url: "http://neudi1fr9mh4edwqa2ori151.wpengine.netdna-cdn.com/wp-content/uploads/2012/04/fried-chicken.jpeg", content: "Fried chicken (also referred to as Southern fried chicken for the variant in the United States) is a dish consisting of chicken pieces usually from broiler chickens which have been floured or battered and then pan-fried, deep fried, or pressure fried. The breading adds a crisp coating or crust to the exterior. What separates fried chicken from other fried forms of chicken is that generally the chicken is cut at the joints, and the bones and skin are left intact. Crisp well-seasoned skin, rendered of excess fat, is a hallmark of well made fried chicken.")
Post.create(user: "Wikipedia", title: "Sushi", photo_url: "https://oyatsubox.com/wp-content/uploads/2016/04/Sushi-header.jpg", content: "Sushi is the Japanese preparation and serving of cooked vinegared rice combined with varied ingredients such as chiefly seafood, vegetables, meat (usually fish), and occasionally tropical fruits. Styles of sushi and its presentation vary widely, but the key ingredient in all cases is the rice, also referred to as shari, or sumeshi.")
Post.create(user: "Wikipedia", title: "Bibimbap", photo_url: "https://images.food52.com/qJoprdD-zzPLp4dWGrQ29wNQWP8=/cea642d5-9ca6-4b91-9ba4-7ea1f9a54b3c--15358124137_3048833c8d_b.jpg", content: "Bibimbap sometimes anglicized as bi bim bap or bi bim bop, is a Korean dish. The word literally means \"mixed rice\". Bibimbap is served as a bowl of warm white rice topped with namul \(sautéed and seasoned vegetables\) and gochujang \(chili pepper paste\), soy sauce, or doenjang \(a fermented soybean paste\). A raw or fried egg and sliced meat \(usually beef\) are common additions. The hot dish is stirred together thoroughly just before eating.")
Post.create(user: "Wikipedia", title: "Steak", photo_url: "http://www.weststeakandseafood.com/wp-content/uploads/2016/05/West_Steak.jpg", content: "A steak is a meat generally sliced perpendicular to the muscle fibers, potentially including a bone. Exceptions, in which the meat is sliced parallel to the fibers, include the skirt steak that is cut from the plate, the flank steak that is cut from the abdominal muscles, and the Silverfinger steak that is cut from the loin and includes three rib bones. When the word \"steak\" is used without qualification, it generally refers to a beefsteak. In a larger sense, there are also fish steaks, ground meat steaks, pork steak and many more varieties of steaks.")
Post.create(user: "Wikipedia", title: "Burrito", photo_url: "http://salsaritas.com/wp-content/uploads/SALSA_MENU_HERO_0003_11-chicken-burrito-20-m-FPO-2.jpg", content: "A burrito is a type of Mexican and Tex-Mex food, consisting of a large wheat flour tortilla with a filling, wrapped into a closed-ended cylinder, in contrast to a taco, where the tortilla is simply folded around the filling. The flour tortilla is sometimes lightly grilled or steamed to soften it, make it more pliable and allow it to adhere to itself when wrapped.")
Post.create(user: "Wikipedia", title: "Galbi", photo_url: "http://seonkyounglongest.com/wp-content/uploads/2016/06/IMG_8790-copy-1000x562.jpg?x61413", content: "Galbi, galbi-gui, or grilled ribs is a type of gui \(grilled dish\) in Korean cuisine. Beef short ribs is often used as the word galbi means \"rib\" in Korean, but pork spareribs and other meat can also be used, in which case the ingredient is specified in the name of the dish. Diners usually cook the ribs on tabletop grills by themselves, as galbi is served freshly cut or cut and marinated in sweet and savory sauce, usually containing soy sauce, garlic, and sugar. Both the non-marinated and the marinated galbi are often featured in Korean barbecue.")
