# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e4cde2eb48e6c0e35657190e8fb5f327f4c74505aae3b7a98a2cd08c6b2a569943039117d49192db6f4526e34ed7a7bad0cc4a01592f40eb7c5456208cc1d5d

test:
  secret_key_base: e11b4d27618b845baa1929cbd538818f77a7a299318fde85904ec2b607f949b64d7673df400559a01a69c72e76f67fa79519631006139257d93392f5645778ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
